# Configuracion de Conectar al Servidor ArchSafio
server_ip=ArchSafio.kinetic.host
server_port=25585
button_text=&a&lConectar al Servidor
remove_realms_button=true
widescreen_mods_button=true
window_title=ArchSafio 1.20.1
