#Configuration file for Enhanced Block Entities
#Fri Sep 25 00:54:42 PET 2026
decorated_pot_ao=false
sign_ao=false
render_enhanced_signs=false
bell_ao=true
shulker_box_ao=false
experimental_signs=false
chest_ao=false
sign_text_rendering=disabled
render_enhanced_decorated_pots=true
experimental_chests=true
christmas_chests=allowed
bed_ao=false
render_enhanced_chests=true
render_enhanced_beds=true
render_enhanced_shulker_boxes=true
experimental_beds=true
render_enhanced_bells=true
force_resource_pack_compat=false
